project:
  type: website
  output-dir: docs

website:
  title: "Bernard Nongpoh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks
      - href: teaching.qmd
        text: Teaching
      - href: posts/index.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
